api/urls.py
from django.urls import path
from .views import *

app_name = "api"

urlpatterns = [
    path('register/', register_user, name='register'),
    path('login/', login_user, name='login'),
    path('verify-token/', VerifyTokenView.as_view(), name='verify-token'),

    path("filter-products/", ProductListView.as_view(), name="product-list"),
    path('products/', AllProductListView.as_view(), name='all-products'),
    path('products/<int:id>/', ProductDetailView.as_view(), name='product-detail'),

    path('product-reviews/<int:product_id>/', ProductReviewListView.as_view(), name='product-reviews'),

    path('category/', CategoryListView.as_view(), name='category-list'),
    path('menu-items/', MenuItemListView.as_view(), name='menu-items'),

    path('apply-cupon/', apply_cupon, name='apply-cupon'),
    path('verify-product-stock/', verify_product_stock, name='verify-product-stock'),

    path('get-company-setting/', get_company_setting, name='get-company-setting'),
    path('place-order/', place_order, name='place-order'),

    path('stripe-webhook/', stripe_webhook, name='stripe-webhook'),
    path("create-checkout-session/", CreateCheckoutSession.as_view(), name="create-checkout-session"),

    path('get-orders/', get_orders, name='get-orders'),
    path('get-order-items/<int:order_id>/', get_order_items, name='get-order-items'),
]

core/urls.py
from django.urls import path
from . import views
from .crud_views import CategoryView

app_name = "core"

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    
    path('products/', views.product, name="product"),

    path('category/', views.category, name="category"),
    path('add-category/', CategoryView.add_category, name="add_category"),

    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

fleet/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('pos/', include('pos.urls')),
    path('api/', include('api.urls')),
    # path('setting/', include('setting.urls')),
    path('product_management/', include('product_management.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/urls.py
from django.urls import path
from .views import *

app_name = "pos"

urlpatterns = [
    path('', pos, name='pos'),
    path('verify_product_size_color/', verify_product_color_size, name='verify_product_color_size'),
    path('verify_product_stock/', verify_product_stock, name='verify_product_stock'),
    path('checkout/', checkout, name='checkout'),
    path('invoice/<int:pos_id>/', invoice, name='invoice'),
]

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
     <!-- Title Meta -->
     <meta charset="utf-8" />
     <title>{% block title %} {% endblock %} | Fleet Ecommerce</title>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta name="description" content="A fully responsive premium admin dashboard template" />
     <meta name="author" content="Techzaa" />
     <meta http-equiv="X-UA-Compatible" content="IE=edge" />

     <!-- App favicon -->
     <link rel="shortcut icon" href="{% static '/assets/images/favicon.ico'  %}">

     <!-- Vendor css (Require in all Page) -->
     <link href="{% static '/assets/css/vendor.min.css' %}" rel="stylesheet" type="text/css" />

     <!-- Icons css (Require in all Page) -->
     <link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />

     <!-- App css (Require in all Page) -->
     <link href="{% static 'assets/css/app.min.css' %}" rel="stylesheet" type="text/css" />

     <!-- Theme Config js (Require in all Page) -->
     <script src="{% static 'assets/js/config.js' %}"></script>

     <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">


     {% block style %} {% endblock %}
</head>

<body>

     <!-- START Wrapper -->
     <div class="wrapper">

          <!-- ========== Topbar Start ========== -->
          {% include 'partials/topbar.html' %}

          <!-- Right Sidebar (Theme Settings) -->
          {% include 'partials/sidebar.html' %}
          <!-- ========== Topbar End ========== -->
        
          <!-- ========== App Menu Start ========== -->

          
          <!-- ========== App Menu End ========== -->

          <!-- ==================================================== -->
          <!-- Start right Content here -->
          <!-- ==================================================== -->
          <div class="page-content">

            <div class="container-fluid">

                {% if messages %}
                    {% for message in messages %}
                        {% if "error" in message.tags %}
                            <div class="alert alert-danger fade show alert-icon" role="alert">
                        {% else %}
                            <div class="alert alert-{{ message.tags }} fade show alert-icon" role="alert">
                        {% endif %}
                                <div class="d-flex align-items-center">
                                    <div class="avatar-sm rounded bg-primary d-flex justify-content-center align-items-center fs-18 me-2 flex-shrink-0">
                                        <i class="bx bx-info-circle text-white"></i>
                                    </div>
                                </div>
                                <div class="flex-grow-1">
                                    {{ message }}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                            </div>
                    {% endfor %}
                {% endif %}

            </div>
            

               <!-- Start Container Fluid -->
               {% block content %} {% endblock %}
               <!-- End Container Fluid -->

               <!-- ========== Footer Start ========== -->
               <footer class="footer">
                   <div class="container-fluid">
                       <div class="row">
                           <div class="col-12 text-center">
                               <script>document.write(new Date().getFullYear())</script> &copy; Finch & Co. All Rights Reserved.
                       </div>
                   </div>
               </footer>
               <!-- ========== Footer End ========== -->

          </div>
          <!-- ==================================================== -->
          <!-- End Page Content -->
          <!-- ==================================================== -->

     </div>
     <!-- END Wrapper -->

     <!-- Vendor Javascript (Require in all Page) -->
     <script src="{% static 'assets/js/vendor.js' %}"></script>

     <!-- App Javascript (Require in all Page) -->
     <script src="{% static 'assets/js/app.js' %}"></script>

     <!-- Vector Map Js -->
     <script src="{% static 'assets/vendor/jsvectormap/js/jsvectormap.min.js' %}"></script>
     <script src="{% static 'assets/vendor/jsvectormap/maps/world-merc.js' %}"></script>
     <script src="{% static 'assets/vendor/jsvectormap/maps/world.js' %}"></script>

     <!-- Dashboard Js -->
     <script src="{% static 'assets/js/pages/dashboard.js' %}"></script>

     {% block scripts %} {% endblock %}

</body>


<!-- Mirrored from techzaa.in/larkon/admin/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 30 Dec 2024 13:39:02 GMT -->
</html>

templates/partials/sidebar.html
{% load static %}
<div class="main-nav">
    <!-- Sidebar Logo -->
    <div class="logo-box">
         <!-- <a href="{% url 'core:dashboard' %}" class="logo-dark">
              <img src="{% static '/assets/images/logo-sm.png' %}" class="logo-sm" alt="logo sm">
              <img src="{% static '/assets/images/logo-dark.png' %}" class="logo-lg" alt="logo dark">
         </a>

         <a href="index.html" class="logo-light">
              <img src="{% static '/assets/images/logo-sm.png'  %}" class="logo-sm" alt="logo sm">
              <img src="{% static '/assets/images/logo-light.png'   %}" class="logo-lg" alt="logo light">
         </a> -->

    </div>

    <!-- Menu Toggle Button (sm-hover) -->
    <button type="button" class="button-sm-hover" aria-label="Show Full Sidebar">
         <iconify-icon icon="solar:double-alt-arrow-right-bold-duotone" class="button-sm-hover-icon"></iconify-icon>
    </button>

    <div class="scrollbar" data-simplebar>
         <ul class="navbar-nav" id="navbar-nav">

              <li class="menu-title">General</li>

              <li class="nav-item">
                   <a class="nav-link" href="{% url 'core:dashboard' %}">
                        <span class="nav-icon">
                             <iconify-icon icon="solar:widget-5-bold-duotone"></iconify-icon>
                        </span>
                        <span class="nav-text"> Dashboard </span>
                   </a>
               </li>

               <li class="nav-item">
                    <a class="nav-link" href="{% url 'pos:pos' %}" role="button" aria-expanded="false" aria-controls="sidebarCategory">
                         <span class="nav-icon">
                              <iconify-icon icon="solar:clipboard-list-bold-duotone"></iconify-icon>
                         </span>
                         <span class="nav-text"> POS </span>
                    </a>
               </li>

              <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:category' %}" role="button" aria-expanded="false" aria-controls="sidebarCategory">
                         <span class="nav-icon">
                              <iconify-icon icon="solar:clipboard-list-bold-duotone"></iconify-icon>
                         </span>
                         <span class="nav-text"> Category </span>
                    </a>
               </li>

              <li class="nav-item">
                   <a class="nav-link" href="{% url 'core:product' %}"  role="button" aria-expanded="false" aria-controls="sidebarProducts">
                        <span class="nav-icon">
                             <iconify-icon icon="solar:t-shirt-bold-duotone"></iconify-icon>
                        </span>
                        <span class="nav-text"> Products </span>
                   </a>
              </li> -->
         </ul>
    </div>
</div>

templates/partials/topbar.html
{% load static %}
<header class="topbar">
    <div class="container-fluid">
         <div class="navbar-header">
              <div class="d-flex align-items-center">
                   <!-- Menu Toggle Button -->
                   <div class="topbar-item">
                        <button type="button" class="button-toggle-menu me-2">
                             <iconify-icon icon="solar:hamburger-menu-broken" class="fs-24 align-middle"></iconify-icon>
                        </button>
                   </div>

                   <!-- Menu Toggle Button -->
                   <!-- <div class="topbar-item">
                        <h4 class="fw-bold topbar-button pe-none text-uppercase mb-0">Welcome!</h4>
                   </div> -->
              </div>

              <div class="d-flex align-items-center gap-1">

                   <!-- Theme Color (Light/Dark) -->
                   <div class="topbar-item">
                        <button type="button" class="topbar-button" id="light-dark-mode">
                             <iconify-icon icon="solar:moon-bold-duotone" class="fs-24 align-middle"></iconify-icon>
                        </button>
                   </div>

                   <!-- Notification -->
                   <!-- <div class="dropdown topbar-item">
                        <button type="button" class="topbar-button position-relative" id="page-header-notifications-dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                             <iconify-icon icon="solar:bell-bing-bold-duotone" class="fs-24 align-middle"></iconify-icon>
                             <span class="position-absolute topbar-badge fs-10 translate-middle badge bg-danger rounded-pill">3<span class="visually-hidden">unread messages</span></span>
                        </button>
                        <div class="dropdown-menu py-0 dropdown-lg dropdown-menu-end" aria-labelledby="page-header-notifications-dropdown">
                             <div class="p-3 border-top-0 border-start-0 border-end-0 border-dashed border">
                                  <div class="row align-items-center">
                                       <div class="col">
                                            <h6 class="m-0 fs-16 fw-semibold"> Notifications</h6>
                                       </div>
                                       <div class="col-auto">
                                            <a href="javascript: void(0);" class="text-dark text-decoration-underline">
                                                 <small>Clear All</small>
                                            </a>
                                       </div>
                                  </div>
                             </div>
                             <div data-simplebar style="max-height: 280px;">
                                  <a href="javascript:void(0);" class="dropdown-item py-3 border-bottom text-wrap">
                                       <div class="d-flex">
                                            <div class="flex-shrink-0">
                                                 <img src="{% static '/assets/images/users/avatar-1.jpg' %}" class="img-fluid me-2 avatar-sm rounded-circle" alt="avatar-1" />
                                            </div>
                                            <div class="flex-grow-1">
                                                 <p class="mb-0"><span class="fw-medium">Josephine Thompson </span>commented on admin panel <span>" Wow 😍! this admin looks good and awesome design"</span></p>
                                            </div>
                                       </div>
                                  </a>
                                  <a href="javascript:void(0);" class="dropdown-item py-3 border-bottom">
                                       <div class="d-flex">
                                            <div class="flex-shrink-0">
                                                 <div class="avatar-sm me-2">
                                                      <span class="avatar-title bg-soft-info text-info fs-20 rounded-circle">
                                                           D
                                                      </span>
                                                 </div>
                                            </div>
                                            <div class="flex-grow-1">
                                                 <p class="mb-0 fw-semibold">Donoghue Susan</p>
                                                 <p class="mb-0 text-wrap">
                                                      Hi, How are you? What about our next meeting
                                                 </p>
                                            </div>
                                       </div>
                                  </a>
                                  <a href="javascript:void(0);" class="dropdown-item py-3 border-bottom">
                                       <div class="d-flex">
                                            <div class="flex-shrink-0">
                                                 <img src="{% static '/assets/images/users/avatar-3.jpg' %}" class="img-fluid me-2 avatar-sm rounded-circle" alt="avatar-3" />
                                            </div>
                                            <div class="flex-grow-1">
                                                 <p class="mb-0 fw-semibold">Jacob Gines</p>
                                                 <p class="mb-0 text-wrap">Answered to your comment on the cash flow forecast's graph 🔔.</p>
                                            </div>
                                       </div>
                                  </a>
                                  <a href="javascript:void(0);" class="dropdown-item py-3 border-bottom">
                                       <div class="d-flex">
                                            <div class="flex-shrink-0">
                                                 <div class="avatar-sm me-2">
                                                      <span class="avatar-title bg-soft-warning text-warning fs-20 rounded-circle">
                                                           <iconify-icon icon="iconamoon:comment-dots-duotone"></iconify-icon>
                                                      </span>
                                                 </div>
                                            </div>
                                            <div class="flex-grow-1">
                                                 <p class="mb-0 fw-semibold text-wrap">You have received <b>20</b> new messages in the
                                                      conversation</p>
                                            </div>
                                       </div>
                                  </a>
                                  <a href="javascript:void(0);" class="dropdown-item py-3 border-bottom">
                                       <div class="d-flex">
                                            <div class="flex-shrink-0">
                                                 <img src="{% static '/assets/images/users/avatar-5.jpg' %}" class="img-fluid me-2 avatar-sm rounded-circle" alt="avatar-5" />
                                            </div>
                                            <div class="flex-grow-1">
                                                 <p class="mb-0 fw-semibold">Shawn Bunch</p>
                                                 <p class="mb-0 text-wrap">
                                                      Commented on Admin
                                                 </p>
                                            </div>
                                       </div>
                                  </a>
                             </div>
                             <div class="text-center py-3">
                                  <a href="javascript:void(0);" class="btn btn-primary btn-sm">View All Notification <i class="bx bx-right-arrow-alt ms-1"></i></a>
                             </div>
                        </div>
                   </div> -->

                   

                   <!-- User -->
                   <div class="dropdown topbar-item">
                        <a type="button" class="topbar-button" id="page-header-user-dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                             <span class="d-flex align-items-center">
                                  <img class="rounded-circle" width="32" src="{% static '/assets/images/users/avatar-1.jpg' %}" alt="avatar-3">
                             </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end">
                             <!-- item-->
                             <h6 class="dropdown-header">{{ request.user.first_name }} {{ request.user.last_name }}</h6>
                             <a class="dropdown-item" href="pages-profile.html">
                                  <i class="bx bx-user-circle text-muted fs-18 align-middle me-1"></i><span class="align-middle">Profile</span>
                             </a>

                             <div class="dropdown-divider my-1"></div>

                             <a class="dropdown-item text-danger" href="{% url 'core:logout' %}">
                                  <i class="bx bx-log-out fs-18 align-middle me-1"></i><span class="align-middle">Logout</span>
                             </a>
                        </div>
                   </div>

                   <!-- App Search-->
                   <form class="app-search d-none d-md-block ms-2">
                        <div class="position-relative">
                             <input type="search" class="form-control" placeholder="Search..." autocomplete="off" value="">
                             <iconify-icon icon="solar:magnifer-linear" class="search-widget-icon"></iconify-icon>
                        </div>
                   </form>
              </div>
         </div>
    </div>
</header>